"""Engine export targets (docs/PRODUCTION.md): naming and packaging only.

The geometry model knows nothing about engines. A target decides how collision proxies are named
so an engine's importer turns them into physics, whether static parts are merged per material
(draw calls), and whether LODs travel as separate files. Only the Godot target is verified in the
engine (tools/engine/godot_check.py); Unity and Unreal follow their documented conventions.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Target:
    name: str
    doc: str
    merge: str  # default static merge: none | by_material
    lod_files: bool  # write <asset>_LOD<n>.glb files
    lods: tuple = ()  # default LOD ratios when the source sets none

    def collision_name(self, asset: str, index: int, convex: bool = True) -> str:
        if self.name == "unreal":
            return f"UCX_{asset}_{index:02d}"  # Unreal: convex collision by name prefix
        if self.name == "godot":
            return f"{asset}_{index:02d}" + ("-convcolonly" if convex else "-colonly")  # Godot: shape only, no visual
        if self.name == "unity":
            return f"{asset}_{index:02d}_collider"  # read extras.collision in an import script
        return f"COL_{asset}_{index:02d}"


TARGETS = {
    "generic": Target("generic", "part nodes kept; collision as COL_ nodes flagged in extras", "none", True, ()),
    "godot": Target("godot", "-convcolonly collision (convex StaticBody shapes), static parts merged per material; "
                    "LODs are generated by Godot's importer", "by_material", False, ()),
    "unity": Target("unity", "static parts merged per material; *_collider nodes flagged in extras (glTF importers do "
                    "not create colliders); LOD files", "by_material", True, (0.5,)),
    "unreal": Target("unreal", "UCX_<mesh>_NN convex collision named after the mesh it belongs to, static parts merged "
                     "per material; LOD files", "by_material", True, (0.5,)),
}
LEGACY_NAMING = {"ucx": "unreal", "godot": "godot"}  # profile export.collision_naming (before Phase 12)


def target_for(profile: dict, asset_export: dict | None = None) -> Target:
    exp = {**(profile.get("export") or {}), **(asset_export or {})}
    name = exp.get("target") or LEGACY_NAMING.get(exp.get("collision_naming", ""), "generic")
    return TARGETS.get(name, TARGETS["generic"])


def export_settings(asset, target: str | None = None) -> dict:
    """Resolved export settings: target, merge, lods. Precedence: `target` argument (sw export --target) >
    the asset's `export:` > the profile's `export:` > the target's defaults."""
    src = dict(asset.source.get("export") or {})
    if target is None:
        target = getattr(asset, "_export_target", None)
    exp = {**(asset.profile.get("export") or {}), **src}
    if target:
        exp = {k: v for k, v in exp.items() if k not in ("target", "collision_naming", "merge", "lods")} | {"target": target}
    t = target_for({"export": exp})
    return {"target": t, "merge": exp.get("merge", t.merge), "lods": list(exp.get("lods", t.lods) or [])}


STATIC = ""  # rigid-group key of parts that never move


def rigid_groups(asset) -> dict[str, list]:
    """Parts grouped by what moves together. A part with a `pivot` (or tagged `separate`) heads a group
    with its whole subtree (a hinged lid with its planks and bands); everything else is static.
    Each group exports as one node with one primitive per material."""
    by_name = {p.name: p for p in asset.parts}
    by_base: dict = {}
    for p in asset.parts:
        by_base.setdefault(p.base, p)

    def head(p, depth=0):
        if p.pivot is not None or "separate" in p.tags:
            return p.name
        parent = by_name.get(p.parent) or by_base.get(p.parent) if p.parent else None
        return head(parent, depth + 1) if parent is not None and depth < 64 else STATIC
    groups: dict = {}
    for p in asset.parts:
        groups.setdefault(head(p), []).append(p)
    return groups


def separate_parts(asset) -> set[str]:
    """Parts that are not in the static group."""
    return {p.name for k, ps in rigid_groups(asset).items() if k != STATIC for p in ps}


def draw_calls(asset, surface) -> int:
    """Primitives the exported file will contain (collision excluded), under the asset's merge policy."""
    def mats(ps):
        out = set()
        for p in ps:
            out |= {m if m else p.material for m in surface.parts[p.name].face_material}
        return out
    if export_settings(asset)["merge"] != "by_material":
        return sum(len(mats([p])) for p in asset.parts)
    return sum(len(mats(ps)) for ps in rigid_groups(asset).values())
