"""Indexed triangle mesh with a typed attribute contract.

The kernel type is an indexed (welded) triangle mesh plus **declared**
attributes. Attributes are not free-form dictionaries: every attribute name
must be registered in :data:`SCHEMA`, which fixes its domain, dtype, width,
default and how it behaves when topology changes. See docs/MESH_MODEL.md.

Domains
    vertex  one value per vertex         (e.g. colour)
    face    one value per triangle       (e.g. provenance, material, region)
    corner  one value per face corner    (e.g. authored / imported UVs)

Face attributes of kind ``label`` are dictionary-encoded: the array holds int32
codes into a per-mesh label table (``mesh.labels[name]``), -1 meaning "unset".
Concatenation remaps codes, so meshes built independently combine safely.

Derived data (normals, tangents) is never stored: it is regenerated by the
surface stage from geometry and shading settings.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field

import numpy as np


@dataclass(frozen=True)
class AttrSpec:
    name: str
    domain: str  # vertex | face | corner
    kind: str  # label | float
    width: int
    default: tuple
    doc: str
    export: str | None = None  # glTF attribute semantic, if exported per vertex


SCHEMA: dict[str, AttrSpec] = {
    s.name: s
    for s in (
        AttrSpec("origin", "face", "label", 1, (-1,), "provenance: source path of the geometry expression that created the face"),
        AttrSpec("material", "face", "label", 1, (-1,), "material name; unset = the part's material"),
        AttrSpec("region", "face", "label", 1, (-1,), "generator-defined surface region (top, bottom, side, cap, cut, ...)"),
        AttrSpec("color", "vertex", "float", 4, (1.0, 1.0, 1.0, 1.0), "linear RGBA vertex colour", "COLOR_0"),
        AttrSpec("uv", "corner", "float", 2, (0.0, 0.0), "authored/imported/locked UV0 per corner", "TEXCOORD_0"),
    )
}
DERIVED = {"normal", "tangent"}  # never stored; regenerated by the surface stage

# What happens to each domain when an operation changes topology. Every op
# declares one topology class (see ops registry); this table is the contract.
POLICY = {
    #             vertex                face                 corner
    "preserve":  ("preserved",         "preserved",         "preserved"),      # transforms, deformers
    "refine":    ("interpolated",      "inherited",         "interpolated"),   # subdivision
    "rebuild":   ("interpolated",      "inherited",         "invalidated"),    # booleans, trims (backend provenance)
    "resample":  ("transferred",       "transferred",       "transferred"),    # decimate (corners via one source face per new face)
    "generate":  ("default",           "assigned",          "absent"),         # generators create fresh geometry
}


class AttributeError_(ValueError):
    pass


def _check(name: str, domain: str | None = None) -> AttrSpec:
    if name in DERIVED:
        raise AttributeError_(f"'{name}' is derived data and cannot be stored on a mesh")
    if name not in SCHEMA:
        raise AttributeError_(f"unknown mesh attribute '{name}' (declare it in mesh.SCHEMA)")
    spec = SCHEMA[name]
    if domain and spec.domain != domain:
        raise AttributeError_(f"'{name}' is a {spec.domain} attribute, not {domain}")
    return spec


@dataclass
class Mesh:
    V: np.ndarray  # (n, 3) float64
    F: np.ndarray  # (m, 3) int64
    vattr: dict = field(default_factory=dict)  # name -> (n, w)
    fattr: dict = field(default_factory=dict)  # name -> (m,) int32 codes or (m, w)
    cattr: dict = field(default_factory=dict)  # name -> (m, 3, w)
    labels: dict = field(default_factory=dict)  # name -> tuple[str, ...]
    invalidated: set = field(default_factory=set)  # attributes dropped by an op

    def __post_init__(self):
        self.V = np.asarray(self.V, dtype=np.float64).reshape(-1, 3)
        self.F = np.asarray(self.F, dtype=np.int64).reshape(-1, 3)
        for d, table, shape in (("vertex", self.vattr, len(self.V)), ("face", self.fattr, len(self.F)), ("corner", self.cattr, len(self.F))):
            for k, v in table.items():
                spec = _check(k, d)
                if len(v) != shape:
                    raise AttributeError_(f"attribute '{k}' has {len(v)} entries, expected {shape}")
                if spec.kind == "label" and k not in self.labels:
                    raise AttributeError_(f"label attribute '{k}' needs a label table")

    # ------------------------------------------------------------------ basics

    def copy(self) -> "Mesh":
        return Mesh(self.V.copy(), self.F.copy(), {k: v.copy() for k, v in self.vattr.items()},
                    {k: v.copy() for k, v in self.fattr.items()}, {k: v.copy() for k, v in self.cattr.items()},
                    dict(self.labels), set(self.invalidated))

    @property
    def n_tris(self) -> int:
        return len(self.F)

    def bounds(self) -> np.ndarray:
        if len(self.V) == 0:
            return np.zeros((2, 3))
        return np.stack([self.V.min(0), self.V.max(0)])

    def center(self) -> np.ndarray:
        b = self.bounds()
        return (b[0] + b[1]) / 2

    def size(self) -> np.ndarray:
        b = self.bounds()
        return b[1] - b[0]

    def triangles(self) -> np.ndarray:
        return self.V[self.F]

    def face_normals(self) -> tuple[np.ndarray, np.ndarray]:
        """Unit normals and areas per face (degenerate faces get a zero normal)."""
        t = self.triangles()
        n = np.cross(t[:, 1] - t[:, 0], t[:, 2] - t[:, 0])
        length = np.linalg.norm(n, axis=1)
        safe = np.where(length > 0, length, 1.0)
        return n / safe[:, None], length / 2

    def volume(self) -> float:
        t = self.triangles()
        return float(np.einsum("ij,ij->i", t[:, 0], np.cross(t[:, 1], t[:, 2])).sum() / 6.0)

    def area(self) -> float:
        return float(self.face_normals()[1].sum())

    # ------------------------------------------------------------------ labels

    def set_label(self, name: str, value: str | None, faces=None) -> "Mesh":
        """Set a face label attribute (all faces, or a boolean/index selection)."""
        spec = _check(name, "face")
        if spec.kind != "label":
            raise AttributeError_(f"'{name}' is not a label attribute")
        table = list(self.labels.get(name, ()))
        codes = self.fattr.get(name, np.full(len(self.F), -1, dtype=np.int32)).copy()
        code = -1
        if value is not None:
            if value not in table:
                table.append(value)
            code = table.index(value)
        if faces is None:
            codes[:] = code
        else:
            codes[faces] = code
        self.fattr[name] = codes
        self.labels[name] = tuple(table)
        return self

    def label_values(self, name: str) -> np.ndarray:
        """Decoded labels per face (object array; None where unset)."""
        codes = self.fattr.get(name)
        if codes is None:
            return np.full(len(self.F), None, dtype=object)
        table = np.array(list(self.labels.get(name, ())) + [None], dtype=object)
        return table[np.where(codes >= 0, codes, len(table) - 1)]

    def set_vertex(self, name: str, values) -> "Mesh":
        spec = _check(name, "vertex")
        self.vattr[name] = np.broadcast_to(np.asarray(values, dtype=np.float64), (len(self.V), spec.width)).copy()
        return self

    def set_corner(self, name: str, values) -> "Mesh":
        spec = _check(name, "corner")
        self.cattr[name] = np.asarray(values, dtype=np.float64).reshape(len(self.F), 3, spec.width).copy()
        self.invalidated.discard(name)
        return self

    # ------------------------------------------------------------------ topology-preserving

    def with_positions(self, V) -> "Mesh":
        """Policy 'preserve': new positions, identical topology and attributes."""
        m = self.copy()
        m.V = np.asarray(V, dtype=np.float64).reshape(-1, 3)
        if m.V.shape != self.V.shape:
            raise AttributeError_("with_positions must keep the vertex count")
        return m

    def translated(self, d) -> "Mesh":
        return self.with_positions(self.V + np.asarray(d, dtype=np.float64))

    def transformed(self, M: np.ndarray) -> "Mesh":
        m = self.with_positions(self.V @ M[:3, :3].T + M[:3, 3])
        if np.linalg.det(M[:3, :3]) < 0:  # mirror: flip winding and keep corners aligned with their vertices
            m.F = m.F[:, ::-1].copy()
            m.cattr = {k: v[:, ::-1].copy() for k, v in m.cattr.items()}
        return m

    def recentered(self) -> "Mesh":
        return self.translated(-self.center())

    def flipped(self) -> "Mesh":
        m = self.copy()
        m.F = m.F[:, ::-1].copy()
        m.cattr = {k: v[:, ::-1].copy() for k, v in m.cattr.items()}
        return m

    def oriented_outward(self) -> "Mesh":
        return self.flipped() if self.volume() < 0 else self.copy()

    # ------------------------------------------------------------------ topology-changing

    def remapped(self, V, F, face_src, vert_src=None, vert_w=None, corner_bary=None, policy: str = "rebuild") -> "Mesh":
        """Build a new mesh and carry attributes across by explicit correspondence.

        face_src:    (m',) index of the source face each new face derives from (-1 = new face)
        vert_src:    (n', k) source vertex indices each new vertex derives from
        vert_w:      (n', k) weights (rows sum to 1); omitted = first column only
        corner_bary: (m', 3, 3) barycentric coords of each new corner inside its source face
                     (enables corner interpolation; omitted = corner attributes invalidated)
        """
        V = np.asarray(V, dtype=np.float64).reshape(-1, 3)
        F = np.asarray(F, dtype=np.int64).reshape(-1, 3)
        face_src = np.asarray(face_src, dtype=np.int64).reshape(-1)
        out = Mesh(V, F, labels=dict(self.labels), invalidated=set(self.invalidated))
        has = face_src >= 0
        for k, v in self.fattr.items():
            new = np.full((len(F),) + v.shape[1:], SCHEMA[k].default[0] if v.ndim == 1 else 0, dtype=v.dtype)
            new[has] = v[face_src[has]]
            out.fattr[k] = new
        if self.vattr:
            if vert_src is None:
                for k in self.vattr:
                    out.invalidated.add(k)
            else:
                idx = np.asarray(vert_src, dtype=np.int64).reshape(len(V), -1)
                w = np.ones_like(idx, dtype=np.float64) if vert_w is None else np.asarray(vert_w, dtype=np.float64).reshape(idx.shape)
                if vert_w is None:
                    w[:, 1:] = 0
                w = w / np.maximum(w.sum(1, keepdims=True), 1e-12)
                for k, v in self.vattr.items():
                    out.vattr[k] = np.einsum("nk,nkw->nw", w, v[idx])
        for k, v in self.cattr.items():
            if corner_bary is None:
                out.invalidated.add(k)
                continue
            src = v[np.clip(face_src, 0, None)]  # (m',3,w) source corner values
            new = np.einsum("mcj,mjw->mcw", np.asarray(corner_bary), src)
            new[~has] = 0
            out.cattr[k] = new
        return out

    def merged(self, decimals: int = 7) -> "Mesh":
        """Weld coincident vertices whose vertex attributes are equal; drop collapsed faces."""
        if len(self.V) == 0:
            return self.copy()
        cols = [np.round(self.V, decimals)] + [np.round(v, 6) for _, v in sorted(self.vattr.items())]
        key = np.concatenate(cols, axis=1)
        # np.unique order (sorted by key) is part of the determinism contract: vertex
        # order feeds seeded ops such as jitter, so changing it changes geometry.
        _, first, inverse = np.unique(key, axis=0, return_index=True, return_inverse=True)
        keep_v = first
        F = inverse.reshape(-1)[self.F]
        keep = (F[:, 0] != F[:, 1]) & (F[:, 1] != F[:, 2]) & (F[:, 0] != F[:, 2])
        out = Mesh(self.V[keep_v], F[keep], {k: v[keep_v] for k, v in self.vattr.items()},
                   {k: v[keep] for k, v in self.fattr.items()}, {k: v[keep] for k, v in self.cattr.items()},
                   dict(self.labels), set(self.invalidated))
        return out.compacted()

    def compacted(self) -> "Mesh":
        used = np.unique(self.F.reshape(-1))
        remap = np.full(len(self.V), -1, dtype=np.int64)
        remap[used] = np.arange(len(used))
        return Mesh(self.V[used], remap[self.F], {k: v[used] for k, v in self.vattr.items()},
                    dict(self.fattr), dict(self.cattr), dict(self.labels), set(self.invalidated))

    def subset(self, faces) -> "Mesh":
        """Split: keep a selection of faces (attributes preserved)."""
        faces = np.asarray(faces)
        return Mesh(self.V, self.F[faces], dict(self.vattr), {k: v[faces] for k, v in self.fattr.items()},
                    {k: v[faces] for k, v in self.cattr.items()}, dict(self.labels), set(self.invalidated)).compacted()

    def to_trimesh(self):  # kept for tests/tools; kernel code must use shapewright.backend
        from . import backend

        return backend.as_trimesh(self)


def count_shells(F: np.ndarray, n: int) -> int:
    """Number of connected pieces (sharing vertices) in a face list."""
    parent = np.arange(n)

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for a, b, c in F:
        ra = find(a)
        parent[find(b)] = ra
        parent[find(c)] = ra
    return len({find(v) for v in np.unique(F)})


def concat(meshes: list[Mesh]) -> Mesh:
    """Merge: concatenate meshes, remapping label codes; missing attributes get defaults."""
    if not meshes:
        return Mesh(np.zeros((0, 3)), np.zeros((0, 3)))
    names_v = sorted({k for m in meshes for k in m.vattr})
    names_f = sorted({k for m in meshes for k in m.fattr})
    names_c = sorted({k for m in meshes for k in m.cattr})
    labels = {k: tuple(dict.fromkeys(lab for m in meshes for lab in m.labels.get(k, ()))) for k in names_f if SCHEMA[k].kind == "label"}
    Vs, Fs, off = [], [], 0
    va = {k: [] for k in names_v}
    fa = {k: [] for k in names_f}
    ca = {k: [] for k in names_c}
    invalid = set()
    for m in meshes:
        Vs.append(m.V)
        Fs.append(m.F + off)
        off += len(m.V)
        invalid |= m.invalidated
        for k in names_v:
            spec = SCHEMA[k]
            va[k].append(m.vattr[k] if k in m.vattr else np.tile(spec.default, (len(m.V), 1)).astype(np.float64))
        for k in names_f:
            if k in m.fattr:
                codes = m.fattr[k]
                if k in labels:
                    table = np.array([labels[k].index(lab) for lab in m.labels.get(k, ())] + [-1], dtype=np.int32)
                    codes = table[np.where(codes >= 0, codes, len(table) - 1)]
                fa[k].append(codes)
            else:
                fa[k].append(np.full(len(m.F), -1, dtype=np.int32))
        for k in names_c:
            if k in m.cattr:
                ca[k].append(m.cattr[k])
            else:
                invalid.add(k)
                ca[k].append(np.zeros((len(m.F), 3, SCHEMA[k].width)))
    return Mesh(np.concatenate(Vs), np.concatenate(Fs), {k: np.concatenate(v) for k, v in va.items()},
                {k: np.concatenate(v) for k, v in fa.items()}, {k: np.concatenate(v) for k, v in ca.items()}, labels, invalid)


def rotation_matrix(deg_xyz) -> np.ndarray:
    """4x4 rotation from XYZ Euler angles in degrees, applied X then Y then Z."""
    rx, ry, rz = np.radians(np.asarray(deg_xyz, dtype=np.float64))
    cx, sx, cy, sy, cz, sz = np.cos(rx), np.sin(rx), np.cos(ry), np.sin(ry), np.cos(rz), np.sin(rz)
    Rx = np.array([[1, 0, 0], [0, cx, -sx], [0, sx, cx]])
    Ry = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]])
    Rz = np.array([[cz, -sz, 0], [sz, cz, 0], [0, 0, 1]])
    M = np.eye(4)
    M[:3, :3] = Rz @ Ry @ Rx
    return M


def translation_matrix(d) -> np.ndarray:
    M = np.eye(4)
    M[:3, 3] = d
    return M


def scale_matrix(s) -> np.ndarray:
    M = np.eye(4)
    M[:3, :3] = np.diag(np.broadcast_to(np.asarray(s, dtype=np.float64), (3,)))
    return M


def region_by_normal(mesh: Mesh, threshold: float = 0.9) -> Mesh:
    """Default region labels: faces whose normal is within ~25 deg of an axis get that side's name."""
    fn, _ = mesh.face_normals()
    names = np.array(["left", "right", "bottom", "top", "back", "front"], dtype=object)
    ax = np.abs(fn).argmax(1)
    sign = (fn[np.arange(len(fn)), ax] > 0).astype(int)
    lab = names[ax * 2 + sign]
    lab[np.abs(fn).max(1) < threshold] = "bevel"
    m = mesh.copy()
    for value in dict.fromkeys(lab):
        m.set_label("region", value, lab == value)
    return m


def geometry_hash(mesh: Mesh, decimals: int = 5) -> str:
    h = hashlib.sha256()
    h.update(np.round(mesh.V, decimals).astype(np.float64).tobytes())
    h.update(mesh.F.astype(np.int64).tobytes())
    return h.hexdigest()[:16]


def geometry_signature(mesh: Mesh) -> dict:
    """Coarse geometry summary that survives cross-platform float noise (the hash does not): see tests/golden.py."""
    return {"tris": mesh.n_tris, "bounds": [[round(float(v), 6) for v in row] for row in mesh.bounds()],
            "area": round(mesh.area(), 8), "volume": round(mesh.volume(), 9)}
